"""
Breed database (Data section) for recognition + info display.
"""

BREED_DATABASE = {
    "Gir": {
        "hindi_name": "गिर",
        "origin": "Gir Forest, Gujarat",
        "state": "Gujarat",
        "type": "Dairy",
        "category": "Cattle",
        "color": "Red to spotted white, sometimes black",
        "horns": "Curved horns resembling half-moon",
        "milk_yield": "10-12 liters/day",
        "lactation": "1200-1800 kg/lactation",
        "fat_content": "4.5-5.0%",
        "weight_male": "545 kg",
        "weight_female": "385 kg",
        "height": "130-135 cm",
        "market_value": "₹80,000 - ₹2,50,000",
        "special": "World-renowned dairy breed, exported to Brazil, USA & Mexico",
        "climate": "Hot and humid tropical",
        "feeding": "Green fodder 25-30 kg, dry fodder 5-6 kg, concentrate 3-4 kg/day",
        "disease_resistance": "High resistance to tick-borne diseases",
        "gestation": "283 days",
        "first_calving": "42-48 months",
        "lifespan": "20-25 years",
        "conservation": "Not threatened",
        "govt_scheme": "Rashtriya Gokul Mission",
    },
    "Sahiwal": {
        "hindi_name": "साहीवाल",
        "origin": "Montgomery (Sahiwal), Punjab",
        "state": "Punjab",
        "type": "Dairy",
        "category": "Cattle",
        "color": "Reddish dun to brown",
        "horns": "Short and stumpy, thick at base",
        "milk_yield": "8-10 liters/day",
        "lactation": "1400-2500 kg/lactation",
        "fat_content": "4.5-5.0%",
        "weight_male": "450-500 kg",
        "weight_female": "300-400 kg",
        "height": "125-135 cm",
        "market_value": "₹70,000 - ₹2,00,000",
        "special": "Best heat-tolerant dairy breed, exported to Africa & Middle East",
        "climate": "Hot and dry climate",
        "feeding": "Green fodder 20-25 kg, dry fodder 4-5 kg, concentrate 3-4 kg/day",
        "disease_resistance": "Good resistance to mastitis",
        "gestation": "283 days",
        "first_calving": "36-42 months",
        "lifespan": "18-22 years",
        "conservation": "Vulnerable",
        "govt_scheme": "National Dairy Plan",
    },
    "Red Sindhi": {
        "hindi_name": "लाल सिंधी",
        "origin": "Karachi & Hyderabad, Sindh",
        "state": "Sindh (Pakistan origin)",
        "type": "Dairy",
        "category": "Cattle",
        "color": "Red, varying from light to dark red",
        "horns": "Fairly small and thick",
        "milk_yield": "6-8 liters/day",
        "lactation": "1100-2200 kg/lactation",
        "fat_content": "4.5-5.5%",
        "weight_male": "400-450 kg",
        "weight_female": "300-350 kg",
        "height": "120-130 cm",
        "market_value": "₹50,000 - ₹1,50,000",
        "special": "Compact body, excellent for crossbreeding programs",
        "climate": "Hot and humid climate",
        "feeding": "Green fodder 18-22 kg, dry fodder 4-5 kg, concentrate 2-3 kg/day",
        "disease_resistance": "Resistant to tick infestation",
        "gestation": "280 days",
        "first_calving": "36-40 months",
        "lifespan": "18-20 years",
        "conservation": "Vulnerable",
        "govt_scheme": "Rashtriya Gokul Mission",
    },
    "Tharparkar": {
        "hindi_name": "थारपारकर",
        "origin": "Tharparkar District, Rajasthan",
        "state": "Rajasthan",
        "type": "Dual Purpose",
        "category": "Cattle",
        "color": "White or light grey",
        "horns": "Medium-sized, upward and backward",
        "milk_yield": "4-6 liters/day",
        "lactation": "800-1800 kg/lactation",
        "fat_content": "4.0-5.0%",
        "weight_male": "450-500 kg",
        "weight_female": "350-400 kg",
        "height": "130-140 cm",
        "market_value": "₹45,000 - ₹1,20,000",
        "special": "Thrives in desert conditions, excellent draught capacity",
        "climate": "Arid and semi-arid regions",
        "feeding": "Green fodder 15-20 kg, dry fodder 5-6 kg, concentrate 2-3 kg/day",
        "disease_resistance": "Excellent resistance to harsh conditions",
        "gestation": "283 days",
        "first_calving": "40-45 months",
        "lifespan": "20-22 years",
        "conservation": "Vulnerable",
        "govt_scheme": "ICAR Desert Cattle Program",
    },
    "Ongole": {
        "hindi_name": "ओंगोल",
        "origin": "Ongole, Andhra Pradesh",
        "state": "Andhra Pradesh",
        "type": "Draught",
        "category": "Cattle",
        "color": "White or light grey with black points",
        "horns": "Short and stumpy",
        "milk_yield": "3-5 liters/day",
        "lactation": "600-1000 kg/lactation",
        "fat_content": "4.5-5.0%",
        "weight_male": "500-600 kg",
        "weight_female": "400-450 kg",
        "height": "140-150 cm",
        "market_value": "₹60,000 - ₹1,80,000",
        "special": "Parent breed of American Brahman cattle, world-famous",
        "climate": "Hot and humid tropical",
        "feeding": "Green fodder 25-30 kg, dry fodder 6-7 kg, concentrate 2-3 kg/day",
        "disease_resistance": "Excellent",
        "gestation": "285 days",
        "first_calving": "42-48 months",
        "lifespan": "20-25 years",
        "conservation": "Not threatened",
        "govt_scheme": "AP Livestock Mission",
    },
    "Hariana": {
        "hindi_name": "हरियाणा",
        "origin": "Rohtak, Hisar, Haryana",
        "state": "Haryana",
        "type": "Dual Purpose",
        "category": "Cattle",
        "color": "White or light grey",
        "horns": "Short, blunt, upward",
        "milk_yield": "6-8 liters/day",
        "lactation": "1000-1600 kg/lactation",
        "fat_content": "4.0-5.0%",
        "weight_male": "450-550 kg",
        "weight_female": "350-400 kg",
        "height": "135-145 cm",
        "market_value": "₹50,000 - ₹1,40,000",
        "special": "Excellent for both milk and agricultural work",
        "climate": "Semi-arid climate",
        "feeding": "Green fodder 20-25 kg, dry fodder 5-6 kg, concentrate 2-3 kg/day",
        "disease_resistance": "Good",
        "gestation": "283 days",
        "first_calving": "40-44 months",
        "lifespan": "18-22 years",
        "conservation": "Vulnerable",
        "govt_scheme": "Haryana Gauvansh Sanrakshan",
    },
    "Kankrej": {
        "hindi_name": "कांकरेज",
        "origin": "Banaskantha, Gujarat-Rajasthan border",
        "state": "Gujarat",
        "type": "Draught",
        "category": "Cattle",
        "color": "Silver grey to iron grey",
        "horns": "Lyre-shaped, long and spreading",
        "milk_yield": "4-6 liters/day",
        "lactation": "800-1400 kg/lactation",
        "fat_content": "4.5-5.0%",
        "weight_male": "500-600 kg",
        "weight_female": "350-450 kg",
        "height": "135-145 cm",
        "market_value": "₹55,000 - ₹1,60,000",
        "special": "Most powerful draught breed, distinctive lyre-shaped horns",
        "climate": "Hot and dry climate",
        "feeding": "Green fodder 22-28 kg, dry fodder 5-6 kg, concentrate 2-3 kg/day",
        "disease_resistance": "Excellent",
        "gestation": "283 days",
        "first_calving": "42-48 months",
        "lifespan": "20-24 years",
        "conservation": "Vulnerable",
        "govt_scheme": "Gujarat Gauseva Commission",
    },
    "Rathi": {
        "hindi_name": "राठी",
        "origin": "Bikaner, Ganganagar, Rajasthan",
        "state": "Rajasthan",
        "type": "Dairy",
        "category": "Cattle",
        "color": "White with brown or black patches",
        "horns": "Small and pointed",
        "milk_yield": "5-7 liters/day",
        "lactation": "900-1500 kg/lactation",
        "fat_content": "4.0-5.0%",
        "weight_male": "350-400 kg",
        "weight_female": "250-300 kg",
        "height": "115-125 cm",
        "market_value": "₹40,000 - ₹1,00,000",
        "special": "Best dairy breed for desert regions, economical to maintain",
        "climate": "Arid and semi-arid",
        "feeding": "Green fodder 15-20 kg, dry fodder 4-5 kg, concentrate 2-3 kg/day",
        "disease_resistance": "Good",
        "gestation": "280 days",
        "first_calving": "38-42 months",
        "lifespan": "18-20 years",
        "conservation": "Vulnerable",
        "govt_scheme": "Rajasthan Gopalan Mission",
    },
    "Murrah Buffalo": {
        "hindi_name": "मुर्रा भैंस",
        "origin": "Rohtak, Hisar, Haryana",
        "state": "Haryana",
        "type": "Dairy",
        "category": "Buffalo",
        "color": "Jet black",
        "horns": "Tightly coiled, spiral shape",
        "milk_yield": "12-18 liters/day",
        "lactation": "1800-2700 kg/lactation",
        "fat_content": "7.0-8.0%",
        "weight_male": "550-650 kg",
        "weight_female": "450-550 kg",
        "height": "135-145 cm",
        "market_value": "₹1,00,000 - ₹3,00,000",
        "special": "WORLD'S BEST dairy buffalo, highest milk producer",
        "climate": "Hot and humid, needs wallowing",
        "feeding": "Green fodder 30-35 kg, dry fodder 6-7 kg, concentrate 4-5 kg/day",
        "disease_resistance": "Good",
        "gestation": "310 days",
        "first_calving": "42-48 months",
        "lifespan": "25-30 years",
        "conservation": "Not threatened",
        "govt_scheme": "National Buffalo Mission",
    },
    "Mehsana Buffalo": {
        "hindi_name": "मेहसाणा भैंस",
        "origin": "Mehsana District, Gujarat",
        "state": "Gujarat",
        "type": "Dairy",
        "category": "Buffalo",
        "color": "Black with white markings",
        "horns": "Medium-sized, curved backward",
        "milk_yield": "8-12 liters/day",
        "lactation": "1400-2200 kg/lactation",
        "fat_content": "7.0-8.0%",
        "weight_male": "500-600 kg",
        "weight_female": "400-500 kg",
        "height": "130-140 cm",
        "market_value": "₹80,000 - ₹2,20,000",
        "special": "Cross between Murrah and Surti, excellent for Gujarat climate",
        "climate": "Hot and dry to semi-arid",
        "feeding": "Green fodder 25-30 kg, dry fodder 5-6 kg, concentrate 3-4 kg/day",
        "disease_resistance": "Good",
        "gestation": "310 days",
        "first_calving": "40-46 months",
        "lifespan": "22-28 years",
        "conservation": "Not threatened",
        "govt_scheme": "Gujarat Buffalo Development",
    },
}

